config/routes.rb
Rails.application.routes.draw do
  
  # we want to add the abilitiy to create, update, delete, and view rooms
  resources :rooms do
  	# because orders are always on rooms, 
  	# we nest the resources (look at railsguides for more info)
  	resources :orders
  	# it is plural because you can place multiple orders
  end

  # sign up
  resources :users
  	resources :orders
  	

  # log in and log out
  # singular resource because we only want to do this once
  resource :session

  # home page is the list of rooms
  root "rooms#index"


end

app/models/order.rb
class Order < ActiveRecord::Base

	# associations
	belongs_to :room
	belongs_to :user

	# validations


	# plugins


	# everything else





end

app/models/room.rb
class Room < ActiveRecord::Base

	# associations
		belongs_to :user
		has_many :orders



	# validations
	validates :name, presence: true
	validates :address, presence: true
	validates :number_of_guests, presence: true, numericality: {greater_than: 0}
	validates :price_in_pence, presence: true,
		numericality: { greater_than_or_equal_to: 50}


	# plugins
	geocoded_by :address
	after_validation :geocode


	# paper clip
	# 960x400#  will  crop the image to 960 by 400
	# 500x    wil make the image 500px wide
	#  x400    will make the image 400px high
	# 960x400    will resize the image to either 960 px wide or 400 high (not crop) note, no hash
	has_attached_file :image, styles: { large: "960x400#",
		medium: "320x200#", thumbnail: "60x60#"}
	# the following line is from the paperclip site, make sure below matches word u used, not avatar
	validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/


	# anything else










end

app/models/rooom.rb
class Rooom < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base


	# associations

		has_many :rooms
		has_many :orders

	# validations
	validates :username, presence: true, uniqueness: true
	validates :email, presence: true, uniqueness: true

	# plugins
	has_secure_password

	# everything else

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


# the application controller manages EVERY controller of the website

# I want there to be a shortcut for finding the current user
# across the whole site
# we decide the name, in this case "current_user"
	def current_user
		if session[:user_id].present?
			User.find(session[:user_id])
		end
	end

# to make the current user method above useful in the views
# add a help method
helper_method :current_user

# add a shortcut to redirect to the sign up page if logged out

	def make_sure_logged_in
		if not current_user.present?
			flash[:error] = "You must be signed up to see this page"
			redirect_to new_user_path
		end
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	# I want to be logged in for ANY area of the orders section
	before_action :make_sure_logged_in
		# he made up the make-sure_logged_in part
		# actions are what happens when you do anything, eg new, create, etc 7 acitons
		# eg, before we do new, it will make us log in


		def new
			# place a new order form
			@room = Room.find(params[:room_id])
			# he is making a new variable called order. on the room we just found (above)
			# the room has many orders and we ant to make a new order
			@order = @room.orders.new
			# to add the current use to the order
			@order.user = current_user
			# could put other features such as @order.starting_at = Time.now
		end

		def create
			# This is actually charging the customer
			@room = Room.find(params[:room_id])
			@order = @room.orders.new(order_params)
			@order.user = current_user

			if @order.save

				# charge them with stripe
				Stripe::Charge.create(amount: @room.price_in_pence, currency: "gbp",
					card: @order.stripe_token, description: "Onboard order")

				# To set up a subscription plan,
				# Stripe::Customer.create(card: @order.stripe_token, plan: "silver",
						# description: "Onboard subscription")

				flash[:success] = "You've ordered this room"
				redirect_to room_path(@room)
			else
				render "new"
			end

		end

		def order_params
			# whitelist the form data
			params.require(:order).permit(:stripe_token)
		end



end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController


	# I want to do a check before certain actions happen (can only see certain pages unless loged in)
	before_action :make_sure_logged_in,
		only: [:new, :create, :edit, :update, :destroy]


		def index
			# this is the homepage
			@rooms = Room.all
		end


		def show
			# this is an individual room
			@room = Room.find(params[:id])
		end

		def new
			# add a new room form
			@room = current_user.rooms.new
		end

		def create
			# actually add the room to the database
			@room = current_user.rooms.new(room_params)

			if @room.save
				flash[:success] = "You've added this room"
				redirect_to room_path(@room)
			else
				render "new"
			end
				
		end

		def edit

			# form for editing the room
			@room = current_user.rooms.find(params[:id])
		end

		def update

			# actually update the database
			@room = current_user.rooms.find(params[:id])

			if @room.update(room_params)
				flash[:success] = "The room has been updated"
				redirect_to room_path(@room)
			else
				render "edit"
			end
		end

		def destroy
			# actually delete the room from the database
			@room = current_user.rooms.find(params[:id])

			@room.destroy

			flash[:success] ="The room has been deleted :("

			redirect_to root_path
		end


		def room_params
			# make sure the form data isnt hacked
			params.require(:room).permit(:name, :address, :description,
				:number_of_guests, :image, :price_in_pence)
		end



	end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController


	def new
		# sign up form
		# no need for any variable because we're not adding anything
		# to the database

	end

	def create
		# INSTRUCTIONS
		# lets get the username and password from the form
		# lets see if there is a user with that username
		# if there is AND the password matches, then login
		# if NOT, dont log in and show an error

		@username = params[:session][:username]
		# within the session form, get the username^
		@password = params[:session][:password]

		@user = User.find_by_username(@username)

		if @user.present? and @user.authenticate(@password)
			# to log in give them a session
			session[:user_id] = @user.id
			flash[:success] = "Welcome back, #{@user.name}"
			redirect_to root_path
		else
			flash[:error] = "Log in failed"
			render "new"
		end

	end



	def destroy
		# log out
		reset_session
		flash[:success] = "You are now logged out"
		redirect_to root_path
	end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		# sign up form
		@user = User.new
	end


	def create
		# actually sign up to the site
		@user = User.new(user_params)

		if @user.save


			# we want to give the user a cookie
			# to let them know who they are
			session[:user_id] = @user.id

			flash[:success] = "Thanks for signing up!"
			redirect_to root_path
		else
			render "new"
		end
	end

	def user_params
		# make sure the form data is white listed
		params.require(:user).permit(:name, :username, :email,
			:password, :password_confirmation )
	end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
    <%= javascript_include_tag "application" %>
  </head>

  <body>

    <div class="row">


        <header class="large-3 columns">
          <h1><%= link_to "Onboard", root_path %></h1>

          <nav>
            <% if current_user.present? %>
              <strong><%= current_user.name %></strong>
              <%= link_to "Add a room", new_room_path %>
              <%= link_to "Log out", session_path, method: :delete %>

            <% else %>
              <%= link_to "Log In", new_session_path %>
              <%= link_to "Sign up", new_user_path %>


            <% end %>
          </nav>

        </header>
          <div class="large-9 columns">
            
            <% if flash[:success].present? %>

              <div data-alert class="alert-box success">
                <%= flash[:success] %>
              </div>
            <% end %>

             <% if flash[:error].present? %>

              <div data-alert class="alert-box alert">
                <%= flash[:error] %>
              </div>
            <% end %>
    

      <%= yield %>

        </div>
      </div>
    
  </body>
</html>

app/views/orders/new.html.erb
<h2>Book this room</h2>

<%= simple_form_for [@room, @order] do |form| %>

  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
<% end %>


<script type="text/javascript" src="https://js.stripe.com/v2/"></script>
<script type="text/javascript">
  // This identifies your website in the createToken call below
  Stripe.setPublishableKey('<%= Rails.application.secrets.stripe_key %>');
  // ...
	  jQuery(function($) {
	  	// we will update the hash below to our variable
	  $('#new_order').submit(function(event) {
	    var $form = $(this);

	    // Disable the submit button to prevent repeated clicks
	    $form.find('button').prop('disabled', true);

	    Stripe.card.createToken($form, stripeResponseHandler);

	    // Prevent the form from submitting with the default action
	    return false;
	  });
	});

	  var stripeResponseHandler = function(status, response) {
  // update this variable as well
  var $form = $('#new_order');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // token contains id, last4, and card type
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    // update the variable here as well
    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};


</script>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |form| %>

	<%= form.input :name %>
	<%= form.input :address %>
	<%= form.input :description %>
	<%= form.input :image %>
	<%= form.input :number_of_guests %>
	<%= form.input :price_in_pence %>

	<%= form.button :submit %>


<% end %>

app/views/rooms/edit.html.erb
<h2>Edit this room</h2>

<%= render "form" %>

app/views/rooms/index.html.erb
<h2>Rooms</h2>

<% @rooms.each do |room| %>
<!-- we have updated this in order to make both the pic and text as links -->
	<div class="room">
		<%= link_to room_path(room) do %>
			<%= image_tag room.image(:thumbnail) %>
			<h3><%= room.name %></h3>
		<% end %>
	</div>

<% end %>

<%= link_to "Add a new room", new_room_path %>

app/views/rooms/new.html.erb
<h2>Add a new room</h2>


<!-- rendering form means that it is rendering what is saved in the partial -->
<%= render "form" %>

app/views/rooms/show.html.erb
<%= image_tag @room.image(:large) %>

<h2><%= @room.name %></h2>

<%= simple_format @room.description %>

<p>
		<strong>Address:</strong>
		<%= @room.address %>
</p>

<% if @room.user.present? %>
	<p>Added by <%= @room.user.username %></p>
<% end %>


<!-- adding the first row makes the edit and delete visible only to the room owner -->
<% if current_user.present? and current_user == @room.user %>
	<div class="actions">

		<%= link_to "Edit", edit_room_path(@room) %>
		<%= link_to "Delete", room_path(@room), method: :delete,
			data: {confirm: "Are you sure?"} %>

	</div>
<% end %>



<%= link_to "Book this room", new_room_order_path(@room) %>

<%= link_to "Back to homepage", root_path %>

app/views/users/new.html.erb
<h2> hello </h2>

<%= simple_form_for @user do |form| %>

	<%= form.input :name %>
	<%= form.input :username %>
	<%= form.input :email %>
	<%= form.input :password %>
	<%= form.input :password_confirmation %>

	<%= form.button :submit %>



<% end %>